<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260120103536 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE article (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, assignement_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_23A0E66698C4682 ON article (assignement_id)');
        $this->addSql('CREATE TABLE assignment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, request_id INT NOT NULL, writer_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_30C544BA427EB8A5 ON assignment (request_id)');
        $this->addSql('CREATE INDEX IDX_30C544BA1BC7E6B6 ON assignment (writer_id)');
        $this->addSql('CREATE TABLE assignment_request (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date DATE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE client (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, subscription_level_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_C7440455381F148B ON client (subscription_level_id)');
        $this->addSql('CREATE TABLE subscription_level (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, min_wait_days INT NOT NULL, max_wait_days INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE writer (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('ALTER TABLE article ADD CONSTRAINT FK_23A0E66698C4682 FOREIGN KEY (assignement_id) REFERENCES assignment (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE assignment ADD CONSTRAINT FK_30C544BA427EB8A5 FOREIGN KEY (request_id) REFERENCES assignment_request (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE assignment ADD CONSTRAINT FK_30C544BA1BC7E6B6 FOREIGN KEY (writer_id) REFERENCES writer (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE client ADD CONSTRAINT FK_C7440455381F148B FOREIGN KEY (subscription_level_id) REFERENCES subscription_level (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE article DROP CONSTRAINT FK_23A0E66698C4682');
        $this->addSql('ALTER TABLE assignment DROP CONSTRAINT FK_30C544BA427EB8A5');
        $this->addSql('ALTER TABLE assignment DROP CONSTRAINT FK_30C544BA1BC7E6B6');
        $this->addSql('ALTER TABLE client DROP CONSTRAINT FK_C7440455381F148B');
        $this->addSql('DROP TABLE article');
        $this->addSql('DROP TABLE assignment');
        $this->addSql('DROP TABLE assignment_request');
        $this->addSql('DROP TABLE client');
        $this->addSql('DROP TABLE subscription_level');
        $this->addSql('DROP TABLE writer');
    }
}
